name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - name: executing remote ssh commands using password 
      uses: appleboy/ssh-action@master 
      with: 
        host: ${{ secrets.TECNOLOGICO_HOST }} 
        username: ${{ secrets.TECNOLOGICO_USER }} 
        password: ${{ secrets.TECNOLOGICO_PASSWORD }} 
        port: ${{ secrets.TECNOLOGICO_PORT }} 
        script: whoami 

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TECNOLOGICO_HOST }}
        username: ${{ secrets.TECNOLOGICO_USER }}
        key: ${{ secrets.TECNOLOGICO_SSHKEY }}
        port: ${{ secrets.TECNOLOGICO_PORT }}
        script: whoami 
